--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ElectroGamesYT/SimpleNPC-1.16.220-Support
build-by-default: true
branches:
- main
projects:
  SimpleNPC-1.16.220-Support:
    path: ""
...
